# Site wide configuration

title:            Commons Logging
locale:           en_US
url:              http://chomman.github.io/blog


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Taehyun Jung
  avatar: https://avatars2.githubusercontent.com/u/1322244?v=3&s=460
  bio: "Software Programmer."
  email: chomman@naver.com
  disqus-shortname: #username
  twitter: JungTaehyun
  facebook: #username
  google:
    plus: chomman
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: chomman
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
